# Generated by Django 4.2.1 on 2024-02-28 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_District',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('role', models.CharField(max_length=15)),
                ('approval_status', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'tb_Login',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=60)),
                ('image', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_State',
            },
        ),
        migrations.CreateModel(
            name='Worker_register',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('contact_number', models.BigIntegerField()),
                ('place', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('proof', models.TextField()),
                ('work_experience', models.CharField(max_length=20)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workerApp.district')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerApp.login')),
            ],
            options={
                'db_table': 'tb_Worker_register',
            },
        ),
        migrations.CreateModel(
            name='User_register',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('contact_number', models.BigIntegerField()),
                ('address', models.TextField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerApp.login')),
            ],
            options={
                'db_table': 'tb_User_register',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_date', models.DateField()),
                ('feedback', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerApp.user_register')),
            ],
            options={
                'db_table': 'tb_Feedback',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workerApp.state'),
        ),
    ]
