# Generated by Django 4.2.1 on 2024-02-28 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workerApp', '0002_worker_register_service_alter_services_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_request',
            fields=[
                ('sr_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('requested_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workerApp.district')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workerApp.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerApp.user_register')),
            ],
            options={
                'db_table': 'tb_Service_request',
            },
        ),
        migrations.CreateModel(
            name='Work_assigns',
            fields=[
                ('wa_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerApp.service_request')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workerApp.worker_register')),
            ],
            options={
                'db_table': 'tb_Work_assigns',
            },
        ),
    ]
