# Generated by Django 4.2.1 on 2024-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerApp', '0003_service_request_work_assigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_register',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
