# Generated by Django 4.0.6 on 2024-03-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workerApp', '0004_worker_register_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_fee',
            fields=[
                ('mf_id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_fee', models.FloatField()),
            ],
            options={
                'db_table': 'tb_Membership_fee',
            },
        ),
        migrations.AddField(
            model_name='worker_register',
            name='student',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='worker_register',
            name='work_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_date', models.DateField()),
                ('membership_validity', models.DateField()),
                ('amount', models.FloatField()),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workerApp.worker_register')),
            ],
            options={
                'db_table': 'tb_Membership',
            },
        ),
    ]
