# Generated by Django 4.0.6 on 2024-03-15 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workerApp', '0005_membership_fee_worker_register_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='service_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workerApp.service_request'),
        ),
    ]
